# Generated by Django 5.0.6 on 2025-10-30 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_user_groups_user_user_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scamrecord',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='scamrecord',
            name='phone_number',
            field=models.CharField(db_index=True, max_length=10),
        ),
    ]
