# Generated by Django 5.0.6 on 2025-10-30 10:15

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_add_pg_trgm_and_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('interaction_type', models.CharField(choices=[('call', 'Call'), ('message', 'Message'), ('spam_report', 'Spam Report')], max_length=20)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('initiator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initiated_interactions', to=settings.AUTH_USER_MODEL)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_interactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['initiator', 'timestamp'], name='app_interac_initiat_9036b3_idx'), models.Index(fields=['receiver', 'timestamp'], name='app_interac_receive_0fd606_idx'), models.Index(fields=['interaction_type'], name='app_interac_interac_22549b_idx')],
            },
        ),
    ]
